### PR TITLE
fix: remove-custom-resource

### LINKED ISSUE #121: remove custom resource
### Now S3.Bucket native support auto delete object.
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-readme.html#bucket-deletion

example code like this:
```ts
const bucket = new Bucket(this, 'MyTempFileBucket', {
  removalPolicy: RemovalPolicy.DESTROY,
  autoDeleteObjects: true,
});
```

I will use this way to auto delete object and remove custom resource.

### PR DESCRIPTION
**Pull request by guan840912**
remove custom resource.
close #121

### CODE REVIEW

**Comment by guan840912** [comment]
Use s3 Bucket `autoDeleteObject` to delete object.
截圖 2021-03-01 上午10 43 09

**Comment by guan840912** [comment]
create stack success. 
截圖 2021-03-01 上午10 51 15
Put `kubeconfig.yaml` and `node-token` to success.
截圖 2021-03-01 上午10 48 25

截圖 2021-03-01 上午10 51 48

**Comment by guan840912** [comment]
Start to destroy stack .
截圖 2021-03-01 上午10 55 37

The object in bucket already been remove.
截圖 2021-03-01 上午10 52 39
  
截圖 2021-03-01 上午10 53 41

**Comment by guan840912** [comment]
Hi @mreferre, Now can been review, thanks ;).

cc @pahud

**Comment by pahud** [comment]
@guan840912 

should we remove `custom-resource-handler/index.py` as well?

**Review by pahud — APPROVED** [review]
LGTM

@mreferre wdyt?

**Review by mreferre — APPROVED** [review]
This LGTM! Thanks for submitting this PR @guan840912

**Pull request merged**
